<?php 
/**
 * Arshad_Vendor extension
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 * 
 * @category   	Arshad
 * @package		Arshad_Vendor
 * @copyright  	Copyright (c) 2014
 * @license		http://opensource.org/licenses/mit-license.php MIT License
 */
/**
 * Vendor list template on product page
 *
 * @category	Arshad
 * @package		Arshad_Vendor
 * @author Ultimate Module Creator
 */
?>
<?php $vendors = $this->getVendorCollection();?>
<?php if ($vendors->count() > 0) :?>
<div class="box-collateral box-vendors box-up-sell">
	<?php foreach ($vendors as $vendor) : ?>
		<div class="item">
				<?php echo $vendor->getName();?><br />
		</div>
	<?php endforeach; ?>
</div>
<?php endif;?>